physics:
  gamma: 1.67
  beta:  0.05
  H_z0:  0.25

time:
  T:  5.0
  dt: 0.000020

grid:
  L_max_global: 800
  L_end:        320
  M_max:        400

convergence:
  threshold:       0.0
  check_frequency: 100

output:
  directory: output
  run_name:  run
  vtk_step:  5000

parallel:
  openmp_threads: 0
